=== GeodeticCitationGeoKey Test

*Test id:* Citation_GeoKey/GeodeticCitationGeoKey

*Requirements:*

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/CitationGeoKeys.ID
|http://www.opengis.net/spec/GeoTIFF/1.1/CitationGeoKeys.type
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoAsciiParamsTag.terminator
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoAsciiParamsTag.NULLWrite
|===

*Purpose:* Verify the contents of the GeodeticCitationGeoKey parameter

*Pre-conditions* The KeyLength and KeyValueOffset values have been set.

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|KeyLength |Parameter |The length of the value for this GeoKey
|KeyValueOffset |Parameter |The location of the GeoKey value in the file
|===

*Test Process:*

    Read the contents of the GeoTIFF file starting at KeyValueOffset up to and including the first NULL.

    Verify that the contents read consists of ASCII characters.

    Verify that the contents read is KeyLength characters long not including the NULL.

    If the content ends with the pipe character (`|`, ASCII decimal code 124),
    verify each entry separated by the `|` character is a key-value pair
    with the key and the value separated by the `=` character (ASCII decimal code 61).

    If the content contains key-value pairs, verify that all keys are one of the following:
    `GCS Name`, `Datum`, `Ellipsoid`, `Primem`, `AUnits`.
