:Title: GeoTIFF Standards Working Group Charter
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2020-11-17
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    14-018r1
|Category: OGC(R) Standards Working Group Charter
|Authors:   Ted Habermann, Scott Simmons
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2020 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group (SWG) is being formed. The OGC members listed below have proposed the OGC GeoTIFF SWG.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The GeoTIFF format has been used for sharing coverage data successfully for years across many platforms and software environments. It is an important de facto standard used primarily for geolocated images. The current GeoTIFF specification (Version 1.8.2) was developed during the 1990’s by a group of interested individuals and has served the community very well since then. The purpose of this SWG is to incorporate the GeoTIFF specification into the OGC standards suite by updating the specification to bring it into conformance with current OGC practices and to provide a forum for evolving the standard in the future, if need be. The resulting candidate standard will strive to maintain compatibility with existing geoTIFF community implementations and practices and future evolution would be done in close cooperation with the existing geoTIFF community.

== Business Value Proposition

The GeoTIFF format is ubiquitous in the geospatial community and is currently used and supported in its ad hoc form by many OCG members. The format forms the basis for sharing a large existing collection of geospatial images and coverage data, it clearly benefits those members to have the standard managed by the OGC membership.

== Scope of Work

This SWG will focus on updating the current specification and aligning it with current practice. We expect this activity to take one year.

The current geoTIFF specification is available at http://trac.osgeo.org/geotiff/. A preliminary discussion of potential refinements to the specification by Frank Warmerdam is available at http://trac.osgeo.org/geotiff/wiki/RefiningGeoTIFF and attached as Annex A.

=== Statement of relationship of planned work to the current OGC Standards baseline

The GeoTIFF format is currently included in extensions the OGC GML Coverages (GMLCOV) 1.0 Standard to the OGC Web Coverage Service (WCS) 2.0 Standard. Standardization of the format will solidify these existing standards.

=== What is Out of Scope?

The SWG will not work on any change requests or other issues beyond those submitted during the 30 day public comment period.

=== Specific Existing Work Used as Starting Point

The current GeoTIFF Specification (Version 1.8.2) is available at http://trac.osgeo.org/geotiff/ . It will serve as the starting point for this SWG.

=== Is This a Persistent SWG

[x] YES

[ ] NO

=== When can the SWG be Inactivated

The GeoTIFF SWG can be inactivated after the following three milestones have been achieved.

1.	The SWG has completed evaluation and incorporation into the candidate standard of all comments received during the public comment period.

2.	Approval by the SWG membership of a recommendation to submit the document to the TC for consideration as an OGC Adopted Standard.

3.	The candidate standard has been approved by the OGC Technical and Planning Committees as an Adopted OGC standard.

== Description of deliverables

////
This section describes what the deliverables will be for this SWG activity. Deliverables could be a revision to an existing Standard, including revisions to schemas. A deliverable could also be a best practices document.

This section also includes a preliminary schedule of activities. For example, an RFC focused SWG schedule would provide a plan and schedule that includes the start date, target date for release of the candidate Standard for public review, date for consolidation of comments, date for edits to document based on comments, and a final target date for making a recommendation to the Membership. This information will be made public and will also be used as input to a RoadMap for the document. Therefore, the more detail the better.
////

=== Initial Deliverables

The GeoTIFF Working Group will deliver a candidate standard to be considered by the TC. The final document will be available in HTML. The details of the schedule will be determined in a discussion during the March 2014 TC.

=== Additional SWG Tasks

==== Task 1: Standardize Cloud-Optimized GeoTIFF

The COG community is willing to turn-over management of the COG specification to OGC. OGC shall develop a GeoTIFF extension that fully documents the COG specification in the manner of an OGC Standard.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

The HDF Group, NASA, NOAA, TBD after discussion during March 2014 TC.

== Domain Working Group Endorsement

No applicable at time of chartering.

== Other informative information about the work of this SWG

=== Collaboration

The GeoTIFF SWG is using and will continue to use GitHub for management of Standard document and related content.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

The GeoTIFF Specification has been developed and maintained on the http://trac.osgeo.org website. This SWG will stay in touch with that group and with Frank Warmerdam as this work progresses. An outline of potential geoTIFF refinements is included as Annex A.

=== Details of first meeting

TBD

=== Projected on-going meeting schedule

TBD

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name |Organization
|Ted Habermann |The HDF Group
|Jeff Walter, Karen Moe |NASA
|===

=== Conveners

Ted Habermann, the HDF Group
Jeff Walter, NASA

[appendix]
:appendix-caption: Annex
==	Refining GeoTIFF

Notes on suggested refinements to the  GeoTIFF 1.0 specification as part of a GeoTIFF standards refinement and publication process at NASA.

===	Projection Parameters

While the original specification offers some example coordinate systems with projection parameters (ie. 3.1.3 Lamber Conformal Conic Aeronautical Chart), and provides a list of general projection parameters (6.2.3) it does not generally indicate what projection parameters are used for which projection methods, nor does it attempt to relate them to any other well known definitions such as EPSG.

I feel it is important to collect a list of projection parameters for each support projection method, and where possible to relate them back to EPSG method and parameter codes for clarity.

To some extent I have attempted to do so at  http://www.remotesensing.org/geotiff/proj_list/ in a way relate connects GeoTIFF, PROJ.4, EPSG and OGC Well Known Text. For the purposes of the GeoTIFF specification I would suggest we stick to offering the GeoTIFF codes, and relating them back to EPSG while enumerating some projection methods and parameters support in GeoTIFF and not in EPSG and clarifying some situations that match poorly between GeoTIFF and EPSG.

===	New Projection Methods and Projection Parameters

Since the original GeoTIFF specification a number of GeoTIFF projection methods and parameters have been added. These should also be reviewed, and if they seem reasonable and in somewhat well understood and common use they should be captured in the specification.

===	Relationship to Newer EPSG Releases

The original GeoTIFF specification was based on the EPSG database in release at the time. Since then the EPSG database has grown and to a limited extent been refactored. While it was not exactly clear how this related to GeoTIFF the accepted industry practice has been to accept newer EPSG PCS and GCS codes even though they are not explicitly listed in the GeoTIFF specification (ie. sections 6.3.2, 6.3.3 and 6.3.4). It is suggested that this be codified into the GeoTIFF specification. We should also likely update sections 6.3.x to reflect a current set of codes or alternatively remove them in favor of a reference to EPSG with a few examples for clarification.

===	PixelAsPoint vs. PixelAsArea

The original GeoTIFF specification was somewhat vague on the implications of using PixelIsPoint? and PixelIsArea? in 2.5.2.2. Some users fell into the trap of thinking that these were only a sampling technique clue and did not affect the real coordinate system. This is not the evolved industry consensus, and the specification needs to make this very clear. Some detail on this issue is captured in: http://trac.osgeo.org/gdal/wiki/rfc33_gtiff_pixelispoint

===	Vertical Coordinate Systems

The information on vertical coordinate systems in the GeoTIFF specification was pretty slim (see 2.5.3.4 and 6.3.4) and and it has taken a long time to establish industry practice on this topic. An effort has been made to suggest best practice at VerticalCS and after review I suggest this make it's way into the specification in some form.

===	TOWGS84GeoKey

One area the original specification left undefined (perhaps deliberately to reflect handling within EPSG) was how transformation between datums should be accomplished. For the most part this is currently accomplished by applications corresponding GCS/Datum codes with the corresponding EPSG definitions and then selecting among the EPSG provided transformations between datums. However, in the area of projected coordinate systems GeoTIFF took the positions that users could either use an existing EPSG PCS/GCS code *or* define details of the coordinate system themselves in the GeoTIFF file. This ability is not available for datums.

As one step towards improved self-defining capability in GeoTIFF that captures much existing industry practice it has been suggested a TOWGS84GeoKey be added essentially corresponding to the OGC WKT TOWGS84 keyword. A proposal in this regard is written up at TOWGS84GeoKey and is in use in at least GDAL based applications: http://trac.osgeo.org/geotiff/wiki/VerticalCS

===	Axis Order

The GeoTIFF spec is vague on axis order issues. Some suggestions on this are made in the  FAQ and some conclusion should likely be codified in the specification - hopefully not in a way that flies in the face of actual industry practice.
