== Requirements
Introduction To Be Provided

Underlying TIFF Requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class TIFF 
^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_TIFF.adoc[]

Requirements Class GeoKeyDirectoryTag
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_GeoKeyDirectoryTag.adoc[]

Requirements Class GeoKeyCode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_GeoKeyCode.adoc[]

Requirements Class GeoAsciiParamsTag
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_GeoAsciiParamsTag.adoc[]

GeoTIFF Configuration GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GTModelTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_GTModelTypeGeoKey.adoc[]

Requirements Class GTRasterTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_GTRasterTypeGeoKey.adoc[]

Requirements Class GTCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_GTCitationGeoKey.adoc[]

Geographic CS Parameter GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GeographicTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeographicTypeGeoKey.adoc[]

Requirements Class GeogCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogCitationGeoKey.adoc[]

Requirements Class GeogGeodeticDatumGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogGeodeticDatumGeoKey.adoc[]

Requirements Class GeogPrimeMeridianGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogPrimeMeridianGeoKey.adoc[]

Requirements Class GeogPrimeMeridianLongGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogPrimeMeridianLongGeoKey.adoc[]

Requirements Class GeogLinearUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogLinearUnitsGeoKey.adoc[]

Requirements Class GeogLinearUnitSizeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogLinearUnitSizeGeoKey.adoc[]

Requirements Class GeogAngularUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogAngularUnitsGeoKey.adoc[]

Requirements Class GeogAngularUnitSizeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogAngularUnitSizeGeoKey.adoc[]

Requirements Class GeogEllipsoidGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogEllipsoidGeoKey.adoc[]

Requirements Class GeogSemiMajorAxisGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogSemiMajorAxisGeoKey.adoc[]

Requirements Class GeogSemiMinorAxisGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogSemiMinorAxisGeoKey.adoc[]

Requirements Class GeogInvFlatteningGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogInvFlatteningGeoKey.adoc[]

Projected CS Parameter GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GeogAzimuthUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_GeogAzimuthUnitsGeoKey.adoc[]

Requirements Class ProjectedCSTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_ProjectedCSTypeGeoKey.adoc[]

Requirements Class PCSCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_PCSCitationGeoKey.adoc[]

Vertical CS Parameter Keys
~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class VerticalCSTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalCSTypeGeoKey.adoc[]

Requirements Class VerticalCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalCitationGeoKey.adoc[]

Requirements Class VerticalDatumGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalDatumGeoKey.adoc[]

Requirements Class VerticalUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalUnitsGeoKey.adoc[]
