== Requirements
Introduction To Be Provided

Underlying TIFF Requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class TIFF 
^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_7_1_1.adoc[]

Requirements Class GeoKeyDirectoryTag
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_7_1_2.adoc[]

Requirements Class GeoKeyCode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_7_1_3.adoc[]

Requirements Class GeoAsciiParamsTag
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/TIFF_Requirements/requirements_class_7_1_4.adoc[]

GeoTIFF Configuration GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GTModelTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_7_2_1.adoc[]

Requirements Class GTRasterTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_7_2_2.adoc[]

Requirements Class GTCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Configuration_Keys/requirements_class_7_2_3.adoc[]

Geographic CS Parameter GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GeographicTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_1.adoc[]

Requirements Class GeogCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_2.adoc[]

Requirements Class GeogGeodeticDatumGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_3.adoc[]

Requirements Class GeogPrimeMeridianGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_4.adoc[]

Requirements Class GeogPrimeMeridianLongGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_5.adoc[]

Requirements Class GeogLinearUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_6.adoc[]

Requirements Class GeogLinearUnitSizeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_7.adoc[]

Requirements Class GeogAngularUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_8.adoc[]

Requirements Class GeogAngularUnitSizeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_9.adoc[]

Requirements Class GeogEllipsoidGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_10.adoc[]

Requirements Class GeogSemiMajorAxisGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_11.adoc[]

Requirements Class GeogSemiMinorAxisGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_12.adoc[]

Requirements Class GeogInvFlatteningGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_7_3_13.adoc[]

Projected CS Parameter GeoKeys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class GeogAzimuthUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_7_4_1.adoc[]

Requirements Class ProjectedCSTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_7_4_2.adoc[]

Requirements Class PCSCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Projected_CS_Parameter_Keys/requirements_class_7_4_3.adoc[]

Vertical CS Parameter Keys
~~~~~~~~~~~~~~~~~~~~~~~~~~

Requirements Class VerticalCSTypeGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_7_5_1.adoc[]

Requirements Class VerticalCitationGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_7_5_2.adoc[]

Requirements Class VerticalDatumGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_7_5_3.adoc[]

Requirements Class VerticalUnitsGeoKey
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_7_5_4.adoc[]
