=== EllipsoidGeoKey Test

*Test id:* Geodetic_CRS_GeoKey/EllipsoidGeoKey

*Requirements:* 

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.reserved
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.EPSG
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.user-defined
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidGeoKey.private
|===

*Purpose:* Verify the contents of the EllipsoidGeoKey parameter

*Pre-conditions* The KeyLength and KeyValueOffset values have been set. 

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|KeyLength |Parameter |The length of the value for this GeoKey
|KeyValueOffset |Parameter |The location of the GeoKey value in the file 
|===

*Test Process:*

    Read a Short value from the GeoTIFF file starting at KeyValueOffset.
    
    Values between 1 and 1000 are only valid for GeoTIFF version 1.0 (obsolete EPSG/POSC codes) 
    
    Values between 1001 and 1023 are invalid (Reserved)
    
    Values between 1024 and 32766 are valid (EPSG codes)
    
    A value of 32767 is valid (User-defined)

    IF value = 32767 THEN verify that there is a GTCitationGeoKey (GeoKey 1026) and EllipsoidSemiMajorAxisGeoKey (GeoKey 2057) in the GeoTIFF file.
 
    IF value = 32767 THEN verify that there is a EllipsoidSemiMinorAxisGeoKey (GeoKey 2058) or an EllipsoidInvFlatteningGeoKey (GeoKey 2059) in the GeoTIFF file.
    
    Values of 32768 through 65535 are valid (private)   
