[appendix]
:appendix-caption: Annex
== Recommendations for including height in model CRS definitions (Informative)

=== Introduction
GeoTIFF 1.0 presently only handles Geographic 2D CRS or Projected CRS (2D) or geocentric (intrinsically 3D) as indicated by the GTModelTypeGeoKey.
A verticalCRS is a 1D gravity-related CRS.
An ellipsoidal height is not a 1D CRS: it can only be used as the height part of a geographic 3D CRS.
In both cases, when the GeoTIFF file contains digital elevation models (Terrain or Surface model,
or gridded bathymetric data), the vertical reference is provided by the compound CRSs mechanism (Horizontal 2D CRS + VerticalGeoKey) documented below.

The value of the VerticalGeoKey may:

* be a verticalCRS (case of 1D gravity-related CRS); or
* describe a geographic 3D CRS (case of ellipsoidal height).

Therefore this key is named VerticalGeoKey (and cannot be called VerticalCRSGeoKey).

Note: In GeoTIFF v1.0 it was called VerticalCSTypeGeoKey.

This specification supports the use of user-defined Vertical CRSs as part of a compound structure, but does not support the definition of user-defined geographic 3D CRSs.

=== Compound CRSs
A future version of GeoTIFF may expand the values of the GTModelTypeGeoKey to explicitly describe the Model CRS being compound.
This document does not make such an expansion.

Recommendation: For a 2D+1D compound CRS comprised of projected CRS + vertical CRS,  GTModelTypeGeoKey value should be 1 and both a ProjectedCRSGeoKey and a VerticalGeoKey should be given. The ProjectedCRSGeoKey should describe a 2D projected CRS, the VerticalGeoKey should describe the vertical CRS.

Recommendation: For a 2D+1D compound CRS comprised of geographic 2D CRS + vertical CRS,  GTModelTypeGeoKey value should be 2 and both a GeodeticCRSGeoKey and a VerticalGeoKey should be given. The GeodeticCRSGeoKey should describe a geographic 2D CRS, the VerticalGeoKey should describe the vertical CRS.

[#section-D-3]
=== Temporary provisions for including ellipsoidal height as one of the coordinates in GeoTIFF

A future version of GeoTIFF may expand the values of the GTModelTypeGeoKey to explicitly differentiate between geographic 2D and geographic 3D CRSs.
This document does not make such an expansion.

In this document there are three possible means of describing ellipsoidal height as one of the coordinates in a GeoTIFF v1.1 file.
All are temporary solutions.

a) Give GTModelTypeGeoKey value of 2 and identify a geographic 2D CRS through the GeodeticCRSGeoKey, giving the ellipsoidal height description by inserting a geographic 3D CRS code in the VerticalGeoKey. The geographic 2D CRS should be the horizontal component of the geographic 3D CRS (this is the **recommended option**).

b) Give GTModelTypeGeoKey value of 1 and identify a projected CRS through the ProjectedCRSGeoKey, giving the ellipsoidal height description by inserting a geographic 3D CRS code in the VerticalGeoKey. The projected CRS should have as its base CRS the geographic 2D CRS which is the horizontal component of the geographic 3D CRS.

NOTE: If the geographic 2D CRS (in case a) or the projected CRS (in case b) would not respect this condition, then a transformation would have to be performed to produce the Lat, Lon that represent the horizontal coordinate values that are to be combined with the Z to get the 3D geographic coordinate, thus introducing some error.

c) give GTModelTypeGeoKey value of 2 and use the VerticalGeoKey to describe an ellipsoid from which the ellipsoid height is measured using the GeoTIFF v1.0 codes in Table D.1 below.

None of these are long-term solutions.
Until a major revision of this specification is available, recommended practice for producers/writers is to use (a).
Readers should be prepared for any of these options.

_Table D.1 - Deprecated codes from GeoTIFF v1.0 indicating Geographic 3D CRS ellipsoid heights (corresponding to option c)_
[cols="4,1",width="90%" options="header"]
|====
<| [underline]#*Ellipsoid Name*#
^| [underline]#*GeoTIFF v1.0 Vertical Code*#
<| Airy_1830_ellipsoid
^| 5001
<| Airy_Modified_1849_ellipsoid
^| 5002
<| ANS_ellipsoid
^| 5003
<| Bessel_1841_ellipsoid
^| 5004
<| Bessel_Modified_ellipsoid
^| 5005
<| Bessel_Namibia_ellipsoid
^| 5006
<| Clarke_1858_ellipsoid
^| 5007
<| Clarke_1866_ellipsoid
^| 5008
<| Clarke_1880_Benoit_ellipsoid
^| 5010
<| Clarke_1880_IGN_ellipsoid
^| 5011
<| Clarke_1880_RGS_ellipsoid
^| 5012
<| Clarke_1880_Arc_ellipsoid
^| 5013
<| Clarke_1880_SGA_1922_ellipsoid
^| 5014
<| Everest_1830_1937_Adjustment_ellipsoid
^| 5015
<| Everest_1830_1967_Definition_ellipsoid
^| 5016
<| Everest_1830_1975_Definition_ellipsoid
^| 5017
<| Everest_1830_Modified_ellipsoid
^| 5018
<| GRS_1980_ellipsoid
^| 5019
<| Helmert_1906_ellipsoid
^| 5020
<| Indonesian_National_Spheroid_ellipsoid
^| 5021
<| International_1924_ellipsoid
^| 5022
<| International_1967_ellipsoid
^| 5023
<| Krassowsky_1940_ellipsoid
^| 5024
<| NWL_9D_ellipsoid
^| 5025
<| NWL_10D_ellipsoid
^| 5026
<| Plessis_1817_ellipsoid
^| 5027
<| Struve_1860_ellipsoid
^| 5028
<| War_Office_ellipsoid
^| 5029
<| WGS_84_ellipsoid
^| 5030
<| GEM_10C_ellipsoid
^| 5031
<| OSU86F_ellipsoid
^| 5032
<| OSU91A_ellipsoid
^| 5033
|====
