[appendix]
:appendix-caption: Annex
== Recommendations for describing compound and geographic 3D CRSs (for grids containing height values)
(Informative)

=== Introduction
It is reminded here that GeoTIFF presently only handles Geographic 2D CRS or Projected 2D CRS, or geocentric (intrinsically 3D) as ModelTypeGeoKey.
It is also reminded that a verticalCRS is a 1D gravity-related CRS and that ellipsoidal height cannot be 1D, only as the height part of a geographic 3D CRS.
In all cases, when the GeoTIFF file contains digital elevation models (Terrain or Surface model, or gridded bathymetric data), the vertical reference is provided by the coumpound CRSs mechanism (Horizontal 2D CRS + VerticalGeoKey) documented below.
However, it should be clear that the value of the VerticalGeoKey may be a verticalCRS (case of 1D gravity-related CRS) or describe a geographic 3D CRS (case of ellipsoïdal height). Therefore this key is named VerticalGeoKey (and can't be called VerticalCRSGeoKey).

=== Compound CRSs
A future version of GeoTIFF may expand the values of the GTModelTypeGeoKey to explicitly describe the Model CRS being compound. This document does not do that.

Recommendation: For a 2D+1D compound CRS comprised of projected CRS + vertical CRS,  GTModelTypeGeoKey value should be 1 and both a ProjectedCRSGeoKey and a VerticalGeoKey should be given. The ProjectedCRSGeoKey should describe a 2D projected CRS.

Recommendation: For a 2D+1D compound CRS comprised of geographic 2D CRS + vertical CRS,  GTModelTypeGeoKey value should be 2 and both a GeodeticCRSGeoKey and a VerticalGeoKey should be given. The GeodeticCRSGeoKey should describe a geographic 2D CRS.

=== Geographic 3D CRS (case of ellipsoïdal height)
A future version of GeoTIFF may expand the values of the GTModelTypeGeoKey to explicitly differentiate between geographic 2D and geographic 3D CRSs. This document does not do that.
In this document there are two possible means of describing a geographic 3D CRS:

a) give GTModelTypeGeoKey value of 2 and identify a geographic 2D CRS through the GeodeticCRSGeoKey, giving the geographic 3D CRS description through the VerticalGeoKey. The geographic 2D CRS should be the horizontal component of the geographic 3D CRS. (This is the **recommended option**)

b) give GTModelTypeGeoKey value of 2 and use the VerticalGeoKey to describe an ellipsoid from which the ellipsoid height is measured using the GeoTIFF v1.0 codes in Table D.1 below.

NOTE: This option is documented only for compatibility with some past Community practices. In this document a 1D ellipsoidal height is an invalid concept and use of these codes is deprecated.

None of these are long-term solutions. Until a major revision of this specification is available, recommended practice for producers/writers is to use (a). Readers should be prepared for any of these options.

[cols="4,1",width="90%" options="header"]
|====
<| [underline]#*Ellipsoid Name*#
^| [underline]#*GeoTIFF v1.0 Vertical Code*#
<| Airy_1830_ellipsoid
^| 5001
<| Airy_Modified_1849_ellipsoid
^| 5002
<| ANS_ellipsoid
^| 5003
<| Bessel_1841_ellipsoid
^| 5004
<| Bessel_Modified_ellipsoid
^| 5005
<| Bessel_Namibia_ellipsoid
^| 5006
<| Clarke_1858_ellipsoid
^| 5007
<| Clarke_1866_ellipsoid
^| 5008
<| Clarke_1880_Benoit_ellipsoid
^| 5010
<| Clarke_1880_IGN_ellipsoid
^| 5011
<| Clarke_1880_RGS_ellipsoid
^| 5012
<| Clarke_1880_Arc_ellipsoid
^| 5013
<| Clarke_1880_SGA_1922_ellipsoid
^| 5014
<| Everest_1830_1937_Adjustment_ellipsoid
^| 5015
<| Everest_1830_1967_Definition_ellipsoid
^| 5016
<| Everest_1830_1975_Definition_ellipsoid
^| 5017
<| Everest_1830_Modified_ellipsoid
^| 5018
<| GRS_1980_ellipsoid
^| 5019
<| Helmert_1906_ellipsoid
^| 5020
<| Indonesian_National_Spheroid_ellipsoid
^| 5021
<| International_1924_ellipsoid
^| 5022
<| International_1967_ellipsoid
^| 5023
<| Krassowsky_1940_ellipsoid
^| 5024
<| NWL_9D_ellipsoid
^| 5025
<| NWL_10D_ellipsoid
^| 5026
<| Plessis_1817_ellipsoid
^| 5027
<| Struve_1860_ellipsoid
^| 5028
<| War_Office_ellipsoid
^| 5029
<| WGS_84_ellipsoid
^| 5030
<| GEM_10C_ellipsoid
^| 5031
<| OSU86F_ellipsoid
^| 5032
<| OSU91A_ellipsoid
^| 5033
|====
_Table D.1 - Deprecated codes from GeoTIFF v1.0 indicating Geographic 3D CRS ellipsoid heights (corresponding to option b)_
