[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

=== General Approach

This GeoTIFF standard specifies an encoding of information for exchange between software components.
As such, this Abstract Test Suite can only validate the conformance of a specific GeoTIFF document.
In most cases, GeoTIFF conformance will be incorporated into the conformance testing of a software component.
These components fall into two categories; GeoTIFF readers and GeoTIFF writers.

Conformance of GeoTIFF readers will validated by the successful processing of a set of representative samples of validated GeoTIFF files.

Conformance of GeoTIFF writers will be validated by the successful validation of a set of representative samples of GeoTIFF files generated by that software component.

=== Conformance Class TIFF
http://www.opengis.net/spec/GeoTIFF/1.1/conf/Core

include::abstract_tests/TIFF_Tests/TEST_TIFF_Core.adoc[]

include::abstract_tests/TIFF_Tests/TEST_TIFF_Tags.adoc[]

include::abstract_tests/TIFF_Tests/TEST_GeoKeyDirectory.adoc[]

include::abstract_tests/TIFF_Tests/TEST_Short_Param.adoc[]

include::abstract_tests/TIFF_Tests/TEST_Double_Param.adoc[]

include::abstract_tests/TIFF_Tests/TEST_Ascii_Param.adoc[]

=== Conformance Class Raster2Model_CoordinateTransformation_GeoKey
http://www.opengis.net/spec/GeoTIFF/1.1/conf/Raster2Model_CoordinateTransformation_GeoKey

include::abstract_tests/Raster2Model_CoordinateTransformation_GeoKeys/TEST_ModelPixelScaleTag.adoc[]

include::abstract_tests/Raster2Model_CoordinateTransformation_GeoKeys/TEST_ModelTiepointTag.adoc[]

include::abstract_tests/Raster2Model_CoordinateTransformation_GeoKeys/TEST_ModelTransformationTag.adoc[]
