== Requirements
Introduction To Be Provided

=== Underlying TIFF Requirements

This Standardization Target addresses the core Requirements Classes applicable to all GeoTIFF files.
 
A GeoTIFF file is a TIFF 6.0 file and inherits the file structure as described in the corresponding portion of the TIFF spec. In addition, all GeoTIFF specific information is encoded in several reserved TIFF tags. The following requirements formalize compliance with TIFF and the GeoTIFF reserved tag structure.    

==== Requirements Class TIFF

A GeoTIFF file is a valid TIFF 6.0 file.

include::requirements/TIFF_Requirements/requirements_class_TIFF.adoc[]

==== Requirements Class GeoKeyDirectoryTag

The GeoKeyDirectoryTag Requirements Class specifies the requirements for implementing the reserved GeoKeyDirectoryTag TIFF tag.

A GeoTIFF file stores projection parameters in a set of "Keys" which are virtually identical in function to a TIFF tag, but have one more level of abstraction above TIFF. Like a tag, a Key has an ID number ranging from 0 to 65535, but unlike TIFF tags, all key ID's are available for use in GeoTIFF parameter definitions.

The Keys in GeoTIFF (also call "GeoKeys") are all referenced from the GeoKeyDirectoryTag tag. The first four keys form the GeoKey Directory Header. The keys which make up this header are; KeyDirectoryVersion, KeyRevision, MinorRevision, and NumberOfKeys.

The GeoKey Directory Header is followed by <NumberOfKeys> Key Entries. Each Key Entry consists of four values:

* "KeyID" gives the key-ID value of the Key (identical in function to TIFF tag ID, but completely independent of TIFF tag-space).
     
* "TIFFTagLocation" indicates which TIFF tag contains the value(s) of the Key: if TIFFTagLocation is 0, then the value is SHORT, and is contained in the "Value_Offset" entry. Otherwise, the type (format) of the value is implied by the TIFF-Type of the tag containing the value.
  
* "Count" indicates the number of values in this key.
   
* "Value_Offset" Value_Offset indicates the index- offset *into* the TagArray indicated by TIFFTagLocation, if it is nonzero. If TIFFTagLocation=0, then Value_Offset contains the actual (SHORT) value of the Key, and Count=1 is implied. Note that the offset is not a byte-offset, but rather an index based on the natural data type of the specified tag array. 

include::requirements/TIFF_Requirements/requirements_class_GeoKeyDirectoryTag.adoc[]

==== Requirements Class GeoKeyCode

include::requirements/TIFF_Requirements/requirements_class_GeoKeyCode.adoc[]

==== Requirements Class GeoShortParams

The following requirements govern the storage of parameter values when there are two or more values of type Short.

include::requirements/TIFF_Requirements/requirements_class_GeoShortParams.adoc[]

==== Requirements Class GeoDoubleParamsTag

The following requirements govern the storage of parameter values when the values are of type Double.

include::requirements/TIFF_Requirements/requirements_class_GeoDoubleParamsTag.adoc[]

==== Requirements Class GeoAsciiParamsTag

The following requirements govern the storage of parameter values when the values are of type ASCII. All text values in a TIFF file must be null-terminated ASCII.

include::requirements/TIFF_Requirements/requirements_class_GeoAsciiParamsTag.adoc[]

=== GeoTIFF Configuration GeoKeys

==== Requirements Class GTModelTypeGeoKey

This GeoKey defines the general type of model Coordinate system used, and to which the raster space will be transformed:unknown, Geocentric (rarely used), Geographic, Projected Coordinate System, or user-defined. If the coordinate system is a PCS, then only the PCS code need be specified. If the coordinate system does not fit into one of the standard registered PCS'S, but it uses one of the standard projections and datums, then its should be documented as a PCS model with "user-defined" type, requiring the specification of projection parameters, etc. 

include::requirements/Configuration_Keys/requirements_class_GTModelTypeGeoKey.adoc[]

==== Requirements Class GTRasterTypeGeoKey

This establishes the Raster Space coordinate system used; there are currently only two, namely RasterPixelIsPoint and RasterPixelIsArea. No user-defined raster spaces are currently supported. For variance in imaging display parameters, such as pixel aspect-ratios, use the standard TIFF 6.0 device-space tags instead.

include::requirements/Configuration_Keys/requirements_class_GTRasterTypeGeoKey.adoc[]

==== Requirements Class GTCitationGeoKey

As with all the "Citation" GeoKeys, this is provided to give an ASCII reference to published documentation on the overall configuration of this GeoTIFF file.

include::requirements/Configuration_Keys/requirements_class_GTCitationGeoKey.adoc[]

=== Geographic CS Parameter GeoKeys

In general, the geographic coordinate system used will be implied by the projected coordinate system code. If however, this is a user-defined PCS, or the ModelType was chosen to be Geographic, then the system must be explicitly defined here, using the Horizontal datum code.

==== Requirements Class GeographicTypeGeoKey

This key may be used to specify the code for the geographic coordinate system used to map lat-long to a specific ellipsoid over the earth.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeographicTypeGeoKey.adoc[]

==== Requirements Class GeogCitationGeoKey

General citation and reference for all Geographic CS parameters.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogCitationGeoKey.adoc[]

==== Requirements Class GeogGeodeticDatumGeoKey

This key may be used to specify the horizontal datum, defining the size, position and orientation of the reference ellipsoid used in user-defined geographic coordinate systems.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogGeodeticDatumGeoKey.adoc[]

==== Requirements Class GeogPrimeMeridianGeoKey

Allows specification of the location of the Prime meridian for user-defined geographic coordinate systems. The default standard is Greenwich, England.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogPrimeMeridianGeoKey.adoc[]

==== Requirements Class GeogPrimeMeridianLongGeoKey

This key allows definition of user-defined Prime Meridians, the location of which is defined by its longitude relative to Greenwich.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogPrimeMeridianLongGeoKey.adoc[]

==== Requirements Class GeogLinearUnitsGeoKey

Allows the definition of geocentric CS linear units for user-defined GCS.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogLinearUnitsGeoKey.adoc[]

==== Requirements Class GeogLinearUnitSizeGeoKey

Allows the definition of user-defined linear geocentric units, as measured in meters.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogLinearUnitSizeGeoKey.adoc[]

==== Requirements Class GeogAngularUnitsGeoKey

Allows the definition of **geocentric** CS Linear units for user-defined GCS and for ellipsoids.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogAngularUnitsGeoKey.adoc[]

==== Requirements Class GeogAngularUnitSizeGeoKey

Allows the definition of user-defined angular geographic units, as measured in radians.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogAngularUnitSizeGeoKey.adoc[]

==== Requirements Class GeogEllipsoidGeoKey

This key may be used to specify the coded ellipsoid used in the geodetic datum of the Geographic Coordinate System.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogEllipsoidGeoKey.adoc[]

==== Requirements Class GeogSemiMajorAxisGeoKey

Allows the specification of user-defined Ellipsoid Semi-Major Axis (a).

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogSemiMajorAxisGeoKey.adoc[]

==== Requirements Class GeogSemiMinorAxisGeoKey

Allows the specification of user-defined Ellipsoid Semi-Minor Axis (b).

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogSemiMinorAxisGeoKey.adoc[]

==== Requirements Class GeogInvFlatteningGeoKey

Allows the specification of the **inverse** of user-defined Ellipsoid's flattening parameter (f). The eccentricity-squared e^2 of the ellipsoid is related to the non-inverted f by:

      e^2 = 2*f - f^2

Note: if the ellipsoid is spherical the inverse-flattening becomes infinite; use the GeogSemiMinorAxisGeoKey instead, and set it equal to the semi-major axis length.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogInvFlatteningGeoKey.adoc[]

==== Requirements Class GeogAzimuthUnitsGeoKey

This key may be used to specify the angular units of measurement used to defining azimuths, in geographic coordinate systems. These may be used for defining azimuthal parameters for some projection algorithms, and may not necessarily be the same angular units used for lat-long.

include::requirements/Geographic_CS_Parameter_Keys/requirements_class_GeogAzimuthUnitsGeoKey.adoc[]

=== Projected CS Parameter GeoKeys

The PCS range of GeoKeys includes the projection and coordinate transformation keys as well. The projection keys are included in this block since they can only be used to define projected coordinate systems.

==== Requirements Class ProjectedCSTypeGeoKey

This code is provided to specify the projected coordinate system.

include::requirements/Projected_CS_Parameter_Keys/requirements_class_ProjectedCSTypeGeoKey.adoc[]

==== Requirements Class PCSCitationGeoKey

As with all the "Citation" GeoKeys, this is provided to give an ASCII reference to published documentation on the Projected  Coordinate System particularly if this is a "user-defined" PCS.

include::requirements/Projected_CS_Parameter_Keys/requirements_class_PCSCitationGeoKey.adoc[]

=== Vertical CS Parameter Keys

==== Requirements Class VerticalCSTypeGeoKey

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalCSTypeGeoKey.adoc[]

==== Requirements Class VerticalCitationGeoKey

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalCitationGeoKey.adoc[]

==== Requirements Class VerticalDatumGeoKey

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalDatumGeoKey.adoc[]

==== Requirements Class VerticalUnitsGeoKey

include::requirements/Vertical_CS_Parameter_Keys/requirements_class_VerticalUnitsGeoKey.adoc[]
