== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== band

well-defined range of wavelengths, frequencies or energies of optical, electric or acoustic radiation

Note 1 to entry: At the pixel level, a band is represented as one of the vector values of the pixel. At image level, band i of an image is the rectangular array of i^th^ sample values from the pixel vectors.

 [Source: 19101-2:2008, 4.1]

=== cell

rectangular area in raster space, in which a single pixel value is filled

=== code

representation of a label according to a specified scheme

 [Source: ISO 19118:2011, 4.3]

=== coordinate

one of a sequence of numbers designating the position of a point

Note 1 to entry: In a spatial coordinate reference system, the coordinate numbers are qualified by units.

 [Source: ISO 19111:2019, 3.1.5]

=== coordinate reference system

coordinate system that is related to an object by a datum

Note 1 to entry:	 Geodetic and vertical datums are referred to as reference frames.

Note 2 to entry:	For geodetic and vertical reference frames, the object will be the Earth. In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.

 [Source: ISO 19111:2019, 3.1.9]

 Note: This term is also called Model Coordinate Reference system in the context of this document.

=== coordinate system

set of mathematical rules for specifying how coordinates are to be assigned to points

 [Source: ISO 19111:2019, 3.1.11]

=== correspondence model
functional relationship between ground and image coordinates based on the correlation be-tween a set of ground control points and their corresponding image coordinates

 [Source: ISO/TS 19130:2010, 4.3]

=== datum
__reference frame__

parameter or set of parameters that realize the position of the origin, the scale, and the orientation of a coordinate system

 [Source ISO 19111:2019, 3.1.15]

=== device space

coordinate space referencing scanner, printers and display devices

=== direct position

position described by a single set of coordinates within a coordinate reference system

=== domain

well-defined set.

Note 1 to entry: Domains are used to define the domain set and range set of operators and functions.

Note 2 to entry: 	Well-defined means that the definition is both necessary and sufficient, as everything that satisfies the definition is in the set and everything that does not satisfy the definition is necessarily outside the set.

 [Souce: 19109:2015, 4.8]

=== double

8-byte IEEE double precision floating point

=== ellipsoid

__reference ellipsoid__

<geodesy> geometric reference surface embedded in 3D Euclidean space formed by an ellipse that is rotated about a main axis

Note 1 to entry: 	For the Earth the ellipsoid is bi-axial with rotation about the polar axis. This results in an oblate ellipsoid with the midpoint of the foci located at the nominal centre of the Earth.

 [Source: ISO 19111:2019, 3.1.22]

=== flattening
__f__

ratio of the difference between the semi-major (a) and semi-minor axis (b) of an ellipsoid to the semi-major axis; f = (a - b)/a

Note 1 to entry:	Sometimes inverse flattening 1/f = a/(a - b) is given instead; 1/f is also known as reciprocal flattening.

 [Source: ISO 19111:2019, 3.1.28]


=== geocoding

translation of one form of location into another

=== geographic coordinate reference system

coordinate reference system that has a geodetic reference frame and an ellipsoidal coordinate system

 [Source: ISO 19111:2019, 3.1.35]

Note: This allows the assignment of a Latitude-Longitude vector to a location on earth (plus optionally a geodetic height).

=== geokey

in GeoTIFF, a GeoKey is equivalent in function to a TIFF tag, but uses a different storage mechanism

=== georectified grid

__rectified grid__

grid for which there is an affine transformation between the grid coordinates and the coordinates of an external coordinate reference system

Note 1 to entry:	If the coordinate reference system is related to the earth by a datum, the grid is a georectified grid.

 [Source: ISO 19123:2005, 4.1.32]

=== georeferencing

geopositioning an object using a Correspondence Model derived from a set of points for which both ground and image coordinates are known

 [Source: ISO 19130:2010, 4.37]

=== GeoTIFF

standard for storing georeference and geocoding information in a TIFF 6.0 compliant raster file

=== grid

network composed of two or more sets of curves in which the members of each set intersect the members of the other sets in an algorithmic way

Note 1 to entry: 	The curves partition a space into grid cells.

 [Source: ISO 19123:2005, 4.1.23]

=== imagery

representation of phenomena as images produced electronically and/or optical techniques

Note 1 to entry:	In this document, it is assumed that the phenomena have been sensed or detected by one or more devices such as radar, cameras, photometers, and infra-red and multispectral scanners

 [Source: 19101-2:2008, 4.14]

=== meridian

intersection of an ellipsoid by a plane containing the shortest axis of the ellipsoid

Note 1 to entry: 	This term is generally used the describe the pole-to-pole arc rather than the complete closed figure.

 [Source: 19111:2019, 3.1.42]


=== metadata

information about a resource

 [Source: ISO 19115-1:2014, 4.10]


=== model space

space in a coordinate reference system related to the earth or a part of the earth

=== mosaic

an image composed of two or more separately collected (sensed) images

Note 1 to entry:	Additional XML metadata may be used to identify the cut-lines (boundaries and parameters for the images used to compose the mosaic.

=== orthorectified grid

orthoimage

georectified grid created using ground control points and elevation data where constant scale is maintained throughout the grid


image in which by orthogonal projection to a reference surface, displacement of image points due to sensor orientation and terrain relief has been removed

Note 1 to entry:	The amount of displacement depends on the resolution and the level of detail of the elevation information and on the software implementation.

=== parallel

line of constant latitude, parallel to the equator

=== pixel

smallest element of a digital image to which attributes are assigned.

Note 1 This term originated as a contraction of “picture element”.

Note 2 Related to the concept of a grid cell.

Note 3 to entry: The intensity of each pixel is variable; in color systems, each pixel has typically three or four dimensions of variability such as red, green and blue, or cyan, magenta, yellow and black.

=== prime meridian

meridian from which the longitudes of other meridians are quantified

 [Source: ISO 19111:2019, 3.1.50]

=== projected coordinate reference system

coordinate reference system derived from a geographic coordinate reference system by applying a map projection

Note 1 to entry:  	May be two- or three-dimensional, the dimension being equal to that of the geographic coordinate reference system from which it is derived.

Note 2 to entry: 	In the three-dimensional case the horizontal coordinates (geodetic latitude and geodetic longitude coordinates) are projected to northing and easting and the ellipsoidal height is unchanged.

 [Source ISO 19111:2019, 3.1.51]

=== projection

projected coordinate reference system

coordinate conversion from an ellipsoidal coordinate system to a plane

 [Source: ISO 19111:2019, 3.1.40]


=== raster

__raster space__

usually rectangular pattern of parallel scanning lines forming or corresponding to the display on a cathode ray tube

 Note 1 to entry:	A raster is a type of grid.

 [Source: ISO 19123:2005, 4.1.30]

=== rational <TIFF>

a RATIONAL value is a fractional value represented by the ratio of two unsigned 4-byte integers

=== rectified grid

grid for which there is an affine transformation between the grid coordinates and the coordinates of an external coordinate reference system

=== referenceable grid

grid associated with a transformation that can be used to convert grid coordinate values to values of coordinates referenced to an external coordinate reference system

=== relative accuracy / relative positional accuracy

evaluation of the random errors in determining the position of one point or feature with respect to another / closeness of coordinate difference value to the true or accepted value in a specified reference system

=== short
2-byte IEEE signed integer

=== tag <TIFF>

a tag is packet of numerical or ASCII values, which have a numerical "Tag" ID indicating their information content

=== vertical coordinate reference system

one-dimensional coordinate reference system based on a vertical reference frame

 [Source: ISO 19111:2019, 3.1.70]
