== Requirements
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

=== Underlying TIFF Requirements

This Standardization Target addresses the core Requirements Classes applicable to all GeoTIFF files.

A GeoTIFF file is a TIFF 6.0 file and inherits the file structure as described in the corresponding portion of the TIFF spec. In addition, all GeoTIFF specific information is encoded in several reserved TIFF tags. The following requirements formalize compliance with TIFF and the GeoTIFF reserved tag structure.

The tags documented in this standard are to be considered completely orthogonal to the raster-data descriptions of the TIFF spec, and impose no restrictions on how the standard TIFF tags are to be interpreted, which color spaces or compression types are to be used, etc.

==== Requirements Class TIFF

A GeoTIFF file is a valid TIFF 6.0 file.

include::requirements/TIFF_Requirements/requirements_class_TIFF.adoc[]

==== Requirements Class GeoKeyDirectoryTag

The GeoKeyDirectoryTag Requirements Class specifies the requirements for implementing the reserved GeoKeyDirectoryTag TIFF tag.

A GeoTIFF file stores projection parameters in a set of "Keys" which are virtually identical in function to a TIFF tag, but have one more level of abstraction above TIFF. Like a tag, a Key has an ID number ranging from 0 to 65535, but unlike TIFF tags, all key ID's are available for use in GeoTIFF parameter definitions.

The Keys in GeoTIFF (also called "GeoKeys") are all referenced from the GeoKeyDirectoryTag tag. The first four keys form the GeoKey Directory Header. The keys which make up this header are: KeyDirectoryVersion, KeyRevision, MinorRevision, and NumberOfKeys.

The GeoKey Directory Header is followed by <NumberOfKeys> Key Entries. Each Key Entry consists of four values:

* "KeyID" gives the key-ID value of the Key (identical in function to TIFF tag ID, but completely independent of TIFF tag-space).

* "TIFFTagLocation" indicates which TIFF tag contains the value(s) of the Key: if TIFFTagLocation is 0, then the value is SHORT, and is contained in the "Value_Offset" entry. Otherwise, the type (format) of the value is implied by the TIFF-Type of the tag containing the value.

* "Count" indicates the number of values in this key.

* "Value_Offset" Value_Offset indicates the index- offset *into* the TagArray indicated by TIFFTagLocation, if it is nonzero. If TIFFTagLocation=0, then Value_Offset contains the actual (SHORT) value of the Key, and Count=1 is implied. Note that the offset is not a byte-offset, but rather an index based on the natural data type of the specified tag array.

include::requirements/TIFF_Requirements/requirements_class_GeoKeyDirectoryTag.adoc[]

==== Requirements Class GeoKeyCode

For consistency, several key codes have the same meaning in all implemented GeoKeys

include::requirements/TIFF_Requirements/requirements_class_GeoKeyCode.adoc[]

The "undefined" code means that this parameter is intentionally omitted or unknown.

In some cases, additional GeoKeys are required when the "User-Defined" is used. Those requirements are included within a Requirements Class where appropriate.

==== Requirements Class GeoShortParamsTag

The following requirements govern the storage of parameter values when there are two or more values of type Short.

include::requirements/TIFF_Requirements/requirements_class_GeoShortParamsTag.adoc[]

==== Requirements Class GeoDoubleParamsTag

The following requirements govern the storage of parameter values when the values are of type Double.

include::requirements/TIFF_Requirements/requirements_class_GeoDoubleParamsTag.adoc[]

==== Requirements Class GeoAsciiParamsTag

The following requirements govern the storage of parameter values when the values are of type ASCII. All text values in a TIFF file must be null-terminated ASCII.

include::requirements/TIFF_Requirements/requirements_class_GeoAsciiParamsTag.adoc[]

Example of a GeoAscii tag containing only one string: "NAD27 / UTM zone 11N\|{NULL}" (where {NULL} is the ASCII character of code 0)

Example of a GeoAscii tag containing two strings: "NAD27 / UTM zone 11N\|NAD27\|{NULL}"

=== GeoTIFF Configuration GeoKeys

This Standardization Target addresses encoding of Configuration values essential for interpreting the rest of the GeoKeys.

==== Requirements Class GTRasterTypeGeoKey

This establishes the Raster Space used; there are currently only two options, namely _RasterPixelIsPoint_ and _RasterPixelIsArea_. No user-defined raster spaces are currently supported. For variance in imaging display parameters, such as pixel aspect-ratios, use the standard TIFF 6.0 device-space tags.
The use of this geokey is *highly recommended* for accurate georeferencing of raster.

include::requirements/Configuration_Keys/requirements_class_GTRasterTypeGeoKey.adoc[]

==== Requirements Class GTModelTypeGeoKey

This GeoKey defines the type of Model coordinate reference system used, to which the transformation from the raster space is made:

*	Model CRS is unknown or unspecified;
*	Model CRS is a Geographic 2D CRS;
*	Model CRS is a Geocentric CRS;
* Model CRS is a Projected CRS;
*	Model CRS is user-defined.

If the Model coordinate reference system is from the GeoTIFF standard CRS register (i.e EPSG register), then only the registered CRS code need be specified. See <<Requirements for definition of Model CRS (when Model CRS is from GeoTIFF CRS register)>>.

If the Model coordinate reference system is not from the GeoTIFF standard CRS register, then it requires the specification of some or all CRS elements. See <<Requirements for definition of user-defined Model CRS>>.

The GeoTIFF v1.0 format has also been used to describe pseudo-3D compound CRSs consisting of a projected CRS and a vertical CRS or a geographic 2D CRS and a vertical CRS, as well as a geographic 3D CRS. In this document, this usage is permitted but not explicitly described through the GTModelTypeGeoKey. Recommendations are given in Annex D.

include::requirements/Configuration_Keys/requirements_class_GTModelTypeGeoKey.adoc[]
NOTE: The GTCitationGeoKey is also provided to give an ASCII reference to published documentation on the overall configuration of the GeoTIFF file (see <<Citation GeoKeys>>).

=== Raster to Model Coordinate Transformation Requirements

For most common applications, the transformation between raster space and model space may be defined with a set of raster-to-model tiepoints and scaling parameters. The _ModelTiepointTag_ and _ModelPixelScaleTag_ may be used for this purpose.

Alternatively, the _ModelTransformationTag_ may be used to specify the transformation matrix between the raster space (and its dependent pixel-value space) and the (possibly 3D) model space.

Consult <<GeoTIFF Tags for Coordinate Transformations>> for a description of their semantics.

NOTE: It should be noted that model space axis order in the following 3 tags _ModelTiepointTag_, _ModelPixelScaleTag_ and _ModelTransformationTag_ is fixed at (lon,lat,height) in case of geographic 2D and (east,north,height) in case of projected regardless of the model space CRS definition. This convention was implicit in GeoTIFF 1.0 and still is valid in this revision.

==== Requirements Class ModelTiepointTag

include::requirements/Raster2Model_CoordinateTransformation_Tags/requirements_class_ModelTiepointTag.adoc[]

==== Requirements Class ModelPixelScaleTag

include::requirements/Raster2Model_CoordinateTransformation_Tags/requirements_class_ModelPixelScaleTag.adoc[]

==== Requirements Class ModelTransformationTag

include::requirements/Raster2Model_CoordinateTransformation_Tags/requirements_class_ModelTransformationTag.adoc[]

=== Requirements for definition of Model CRS (when Model CRS is from GeoTIFF CRS register)

==== Overview

When the Model CRS is included in the GeoTIFF CRS register (i.e EPSG register), only its register code is required. For 2D projected CRSs ("map grids") the code is given through the ProjectedCRSGeoKey. For geodetic CRSs (geographic 2D and geocentric CRSs) the code is given through the GeodeticCRSGeoKey. If the Model CRS is a pseudo-3D compound CRS consisting of either a projected 2D CRS or a geographic 2D CRS together with a vertical CRS, the code of the vertical component is given through the VerticalGeoKey.

NOTE: It is a practice in some Communities to indicate a geographic 3D CRS (with ellipsoidal height) by including the code of the geographic 3D CRS in a VerticalGeoKey. See Annex D.

==== ProjectedCRSGeoKey

This key is used to specify the projected coordinate reference system from the GeoTIFF CRS register or to indicate that the Model CRS is a user-defined
projected coordinate reference system.

NOTE: In GeoTIFF 1.0 this key was called ProjectedCSTypeGeoKey

include::requirements/Projected_CRS_GeoKey/requirements_class_ProjectedCRSGeoKey.adoc[]

==== GeodeticCRSGeoKey

This key is provided to specify the geodetic (geographic or geocentric) coordinate reference system from the GeoTIFF CRS register or to indicate that the Model CRS is a user-defined geodetic coordinate reference system.

NOTE: In GeoTIFF 1.0 this key was called GeographicTypeGeoKey. Geodetic CRS is a superset of geographic 2D CRS, geographic 3D CRS and geocentric (earth-centred 3D Cartesian) CRS.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_GeodeticCRSGeoKey.adoc[]

==== VerticalGeoKey

This key is provided to specify the vertical coordinate reference system from the GeoTIFF CRS register or to indicate that the CRS is a user-defined vertical coordinate reference system.

NOTE: In GeoTIFF 1.0 this key was called VerticalCSTypeGeoKey. In GeoTIFF v1.0 vertical coordinate reference systems were described in draft form, with the statement "Vertical coordinate systems are not yet implemented. These sections are provided for future development, and any vertical coordinate systems in the current revision must be defined using the VerticalCitationGeoKey".

include::requirements/Vertical_GeoKeys/requirements_class_VerticalGeoKey.adoc[]

==== Citation GeoKeys
The _GTCitationGeoKey_ is provided to give an ASCII reference to published documentation on the overall configuration of the GeoTIFF file.
The _GeodeticCitationGeoKey_, _ProjectedCitationGeoKey_ and _VerticalCitationGeoKey_ are used to describe Model CRS elements through ASCII free text. A citation may be included with a CRS identified through the GeoTIFF CRS register (<<Requirements for definition of Model CRS (when Model CRS is from GeoTIFF CRS register)>>). A citation is mandatory for a user-defined CRSs and CRS objects (<<Requirements for definition of user-defined Model CRS>>). The _GeodeticCitationGeoKey_, _ProjectedCitationGeoKey_ and _VerticalCitationGeoKey_ are used with CRSs and CRS components.

NOTE: In GeoTIFF 1.0 the GeodeticCitationGeoKey key was called GeogCitationGeoKey and the ProjectedCitationGeoKey key was called PCSCitationGeoKey

include::requirements/Citation_Keys/requirements_class_CitationGeoKeys.adoc[]

=== Requirements for definition of user-defined Model CRS

The GeoKeys described in this section are needed only when Model CRSs are not available from the GeoTIFF CRS register and the CRS or one or more of its component objects is user-defined, that is if one or more of ProjectedCRSGeoKey, GeodeticCRSGeoKey or VerticalGeoKey has a value of 32767.

NOTE: Anyone not interested in constructing a user-defined model CRS can ignore this section.

NOTE: It should be noted that the implicit axis order of user-defined CRS definitions is fixed at (lon,lat,height) in case of geographic and (east,north,height) in case of projected regardless of the model space CRS definition. This convention was implicit in GeoTIFF 1.0 and still is valid in this revision. As with GeoTIFF 1.0, it is not possible to express a user-defined CRS that deviates from this axis order convention. The intention is to address this limitation in a future revision.

==== Units GeoKeys

These keys are used to specify Units of Measure (UoM) through the identification of a unit from the GeoTIFF CRS register or to indicate that the unit is user-defined

The *GeogAngularUnitsGeoKey* key is used to specify the angular unit for:

*	the axes in user-defined geographic 2D CRSs;
*	the horizontal axes in user-defined geographic 3D CRSs;
*	the longitude from the reference meridian in user-defined prime meridians;
*	user-defined map projection parameters that are angles.

The *GeogAzimuthUnitsGeoKey* key is used to specify the angular unit for user-defined map projection parameters when these differ from the angular unit described through the GeogAngularUnitsGeoKey.

The *GeogLinearUnitsGeoKey* key is used to specify the linear unit for:

*   the axes in user-defined geocentric Cartesian CRSs;
*	the height axis of a user-defined geographic 3D CRS;
*	for user-defined ellipsoid axes.

The *ProjLinearUnitsGeoKey* key is used to specify the linear units for:

*	the axes of  a user-defined projected CRS;
*	map projection parameters that are lengths.

The *VerticalUnitsGeoKey* key is used to specify the linear unit for:

*	the axis of a user-defined vertical CRS.

include::requirements/Units_Keys/requirements_class_UnitsGeoKeys.adoc[]

==== Unit Size GeoKeys
These keys allow the definition of size of user-defined angular and linear units, given in the SI base unit for that unit type (meters for length, radians for angle).

Note: this specification does not support user-defined units for vertical coordinate reference systems.

include::requirements/Units_Keys/requirements_class_UnitSizeGeoKeys.adoc[]

==== Geodetic Datum

===== GeodeticDatumGeoKey

This key is used to specify a geodetic datum from the GeoTIFF CRS register, or to indicate that the geodetic datum or one or both of its component ellipsoid or prime meridian is user-defined.

NOTE: In GeoTIFF 1.0 this key was called GeogGeodeticDatumGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_GeodeticDatumGeoKey.adoc[]

===== PrimeMeridianGeoKey

This key is used to specify a Prime Meridian from the GeoTIFF CRS register or to indicate that the Prime Meridian is user-defined. The default is Greenwich, England.

NOTE: In GeoTIFF 1.0 this key was called GeogPrimeMeridianGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_PrimeMeridianGeoKey.adoc[]

===== PrimeMeridianLongitudeGeoKey

This key allows definition of a user-defined Prime Meridian, the location of which is defined by its
longitude relative to the international reference meridian (for the earth this is Greenwich).

NOTE: In GeoTIFF 1.0 this key was called GeogPrimeMeridianLongGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_PrimeMeridianLongitudeGeoKey.adoc[]

===== EllipsoidGeoKey
This key is provided to specify an ellipsoid (or sphere) from the GeoTIFF CRS register or to indicate that the ellipsoid (or sphere) is user-defined.

NOTE: In GeoTIFF 1.0 this key was called GeogEllipsoidGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_EllipsoidGeoKey.adoc[]

===== Ellipsoid parameter GeoKeys

These keys are used to specify the size and shape of a user-defined ellipsoid or sphere used as the model of the earth. Only bi-axial ellipsoids and spheres are catered for. An ellipsoid is defined through two parameters,
its semi-major axis _(a)_

and either its semi-minor axis _(b)_ or its inverse flattening _(1/f)_ where __1/f = a/(a - b)__.

If the model is a sphere, _1/f_ is infinite so _a_ and _b_ must be used, with the value of _b_ set to that of __a__.

*EllipsoidSemiMajorAxisGeoKey*

This key is provided to specify the first defining parameter of a user-defined bi-axial ellipsoid  or a user-defined sphere. It allows the specification of the ellipsoid semi-major axis _(a)_ or the sphere's radius.

NOTE: In GeoTIFF 1.0 this key was called GeogSemiMajorAxisGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_EllipsoidSemiMajorAxisGeoKey.adoc[]

*EllipsoidSemiMinorAxisGeoKey*

This key is provided to specify the second defining parameter of a user-defined bi-axial ellipsoid or of a user-defined sphere. It allows the specification of the ellipsoid semi-minor axis _(b)_ or the sphere's radius.

NOTE: In GeoTIFF 1.0 this key was called GeogSemiMinorAxisGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_EllipsoidSemiMinorAxisGeoKey.adoc[]

*EllipsoidInvFlatteningGeoKey*

This key is provided to specify the second defining parameter of a user-defined bi-axial ellipsoid. It allows the specification of the ellipsoid inverse flattening __(1/f)__. It is a ratio and does not require a unit.

NOTE: In GeoTIFF 1.0 this key was called GeogInvFlatteningGeoKey.

include::requirements/Geodetic_CRS_GeoKeys/requirements_class_EllipsoidInvFlatteningGeoKey.adoc[]

==== Vertical Datum

This key may be used to specify the vertical datum for a user-defined vertical coordinate reference system.

include::requirements/Vertical_GeoKeys/requirements_class_VerticalDatumGeoKey.adoc[]

==== Map Projection GeoKeys

===== Requirements Class ProjectionGeoKey

The _ProjectionGeoKey_ key is used to specify a map projection from the GeoTIFF CRS register or to indicate that the map projection is user-defined. In the EPSG Dataset a map projection is a coordinate conversion, a subtype of coordinate operation.

include::requirements/Projection_Definition_Keys/requirements_class_ProjectionGeoKey.adoc[]

===== Requirements Class ProjMethodGeoKey (coordinate operation method)

The _ProjMethodGeoKey_ key is used to specify a map projection method from the GeoTIFF v1.0 coordinate transformation code list (Annex C), or to indicate that the map projection method is user-defined.

NOTE: In GeoTIFF 1.0 this key was called ProjCoordTransGeoKey.

NOTE: GeoTIFF v1.0 did not make reference to the EPSG coordinate operation methods (a future version of GeoTIFF might do this).

include::requirements/Projection_Definition_Keys/requirements_class_ProjMethodGeoKey.adoc[]

===== Map Projection parameters (coordinate operation parameters)

Each map projection method requires several map projection parameters (coordinate operation parameters). GeoTIFF v1.0 did not specify which parameters should be associated with which methods, nor make reference to the EPSG coordinate operation parameters associated with each method (a future version of GeoTIFF might do this).

include::requirements/Projection_Definition_Keys/requirements_class_ProjAngularParameters.adoc[]

include::requirements/Projection_Definition_Keys/requirements_class_ProjAzimuthAngleGeoKey.adoc[]

include::requirements/Projection_Definition_Keys/requirements_class_ProjLinearParameters.adoc[]

include::requirements/Projection_Definition_Keys/requirements_class_ProjScalarParameters.adoc[]
