== Clauses not Containing Normative Material

The following sections of this standard are included for informative purposes only.
These sections serve to assist in correct implementation of this standard but do not impose any additional requirements.

* <<clause_8_media_types.adoc#, Media Types for GeoTIFF data encoding>>: This informative clause documents the MIME type usages for GeoTIFF files.

* <<annex-a.adoc#,Annex B: The GeoTIFF File Structure>>: This Annex provides a description of the community GeoTIFF specification and supporting information on how various elements of that specification should be used.

* <<annex-d.adoc#,Annex D: Recommendations for describing compound and geographic 3D CRSs>>: This Annex provides recommendations for describing 3D Model CRS subtypes to which heights are referenced (compound and geographic 3D) that are not fully supported in this community specification.

* <<annex-e.adoc#,Annex E: Summary of GeoKey IDs and names>>: This Annex lists the names and IDs of all GeoKeys supported in this specification.

* <<annex-f.adoc#,Annex F: Examples>>: This Annex contains a set of illustrative examples of GeoTIFF tags' contents.

* <<annex-g.adoc#,Annex G: Deprecated and deleted EPSG codes>>: This Annex documents EPSG codes explicitly cited in the 1995 v1.0 GeoTIFF specification that are no longer valid.

* <<annex-h.adoc#,Annex H: Backward compatibility>>: This Annex documents backward compatibility of this minor revision with revision 1.0 of GeoTIFF and the changes in this document from the 1995 v1.0 GeoTIFF specification.
