== Conformance
This standard defines 120 Requirements grouped into 29 Requirements Classes.

These Requirements address five (5) standardization target types:

* Underlying TIFF Requirements
* GeoTIFF Configuration GeoKeys
* Geographic CRS Parameter GeoKeys
* Projected CRS Parameter GeoKeys
* Vertical CRS Parameter GeoKeys

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® encoding standard, a software implementation shall comply with all of the conformance classes specified in Annex A (normative).

This version 1.0 of the OGC® GeoTIFF standard is a formalized version of the GeoTIFF specification currently in common use. Any discrepancies between this specification and the community GeoTIFF standard identified in Chapter 3 should be brought to the attention of the OGC® for resolution.
