==== Requirements Class GeoDoubleParamsTag
http://www.opengis.net/spec/GeoTIFF/0.0/GeoDoubleParamsTag

[cols=">20h,<80d",width="100%"]
|===
<|Test id: |http://www.opengis.net/spec/GeoTIFF/0.0/GeoDoubleParamsTag
2+<|Requirements: +
 - The GeoDoubleParamsTag SHALL have ID = 34736 +
 - The GeoDoubleParamsTag MAY hold any number of key parameters with type = Double
<|Test purpose: | Verify all GeoKeys who's values are of type double
2+<|Test method:
2+<| Locate TIFF tag 34736

For each GeoKey in the directory +
  1) Locate the GeoKey value in table +
  2) Execute the corresponding test
|===

[[Double_GeoKey_Tests]]
[cols="2,4",width="100%", options="header"]
|===
^| GeoKey 
^| Test
^| 2053 <| GeodeticCRSParameterKeys/GeogLinearUnitSizeGeoKey
^| 2055 <| GeogAngularUnitSizeGeoKey
^| 2057 <| EllipsoidSemiMajorAxisGeoKey
^| 2058 <| EllipsoidSemiMinorAxisGeoKey
^| 2059 <| EllipsoidInvFlatteningGeoKey
^| 2061 <| PrimeMeridianLongitudeGeoKey
^| 3077 <| ProjectedCRSParameterKeys/ProjLinearUnitSizeGeoKey
^| 3078 <| ProjStdParallel1GeoKey
^| 3079 <| ProjStdParallel2GeoKey
^| 3080 <| ProjNatOriginLongGeoKey
^| 3081 <| ProjNatOriginLatGeoKey
^| 3082 <| ProjFalseEastingGeoKey
^| 3083 <| ProjFalseNorthingGeoKey
^| 3084 <| ProjFalseOriginLongGeoKey
^| 3085 <| ProjFalseOriginLatGeoKey
^| 3086 <| ProjFalseOriginEastingGeoKey
^| 3087 <| ProjFalseOriginNorthingGeoKey
^| 3088 <| ProjCenterLongGeoKey
^| 3089 <| ProjCenterLatGeoKey
^| 3090 <| ProjCenterEastingGeoKey
^| 3091 <| ProjCenterNorthingGeoKey
^| 3092 <| ProjScaleAtNatOriginGeoKey
^| 3093 <| ProjScaleAtCenterGeoKey
^| 3094 <| ProjAzimuthAngleGeoKey
^| 3095 <| ProjStraightVertPoleLongGeoKey
|===

Double GeoKey Tests