==== Double Parameters Test

*Test id:* TIFF_Test/DoubleParameters

*Requirements:* 

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.KeyEntry.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryTIFFTagLocation 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryKeyCount 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryValueOffset
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoDoubleParamsTag.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoDoubleParamsTag.count
|http://www.opengis.net/spec/GeoTIFF/1.1/PrimeMeridianLongitudeGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/PrimeMeridianLongitudeGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/UnitSizeGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/UnitSizeGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidSemiMajorAxisGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidSemiMajorAxisGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidSemiMinorAxisGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidSemiMinorAxisGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidInvFlatteningGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/EllipsoidInvFlatteningGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjAngularParameterGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjAngularParameterGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjLinearParameterGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjLinearParameterGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjScalarParameterGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjScalarParameterGeoKey.type
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjAzimuthAngleGeoKey.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/ProjAzimuthAngleGeoKey.type
|===

*Purpose:* Verify a Double parameter

*Pre-conditions* The GeoKeyDirectory, DoubleValues and GeoKeyOffset values have been set. 

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|GeoKeyDirectory |Global |Location of the GeoTIFF GeoKey directory
|DoubleValues |Global |Location of the Double values for GeoTIFF Double GeoKeys
|GeoKeyOffset |Parameter| Location of this Key Entry Set in the GeoKey directory
|GeoKey |Local |Temporary value of the GeoKey
|KeyLength |Local |Temporary value for the length of the value for the GeoKey
|KeyValueOffset |Local |The location of the GeoKey value in the file 
|===

*Test Process:*

    Locate the Key Entry Set using the GeoKeyDirectory and GeoKeyOffset values.

    Process the second Short integer in the Key Entry Set
        {
        IF value != 34736 THEN error out
        }
    Process the first Short integer in the Key Entry Set
        {
        Set GeoKey to the value
        }
    Process the third Short integer in the Key Entry Set
        {
        Set KeyLength to the value
        }
    Process the fourth Short integer in the Key Entry Set
        {
        SET KeyValueOffset to the value
        }
    SET KeyValueOffset = DoubleValues + (KeyValueOffset * 8)

    Validate the parameter
        Locate the GeoKey value in the following table
        Execute the corresponding test passing KeyLength and KeyValueOffset as parameters

[[Double_GeoKey_Tests]]
[cols="2,4",width="100%", options="header"]
|===
^| GeoKey ^| Test
^| 0 <| ignore
^| 2053 <| Units_GeoKeys/UnitSizeGeoKey (Geog Linear)
^| 2055 <| Units_GeoKeys/UnitSizeGeoKey (Geog Angular)
^| 2057 <| Geodetic_CRS_GeoKey/EllipsoidSemiMajorAxisGeoKey
^| 2058 <| Geodetic_CRS_GeoKey/EllipsoidSemiMinorAxisGeoKey
^| 2059 <| Geodetic_CRS_GeoKey/EllipsoidInvFlatteningGeoKey
^| 2061 <| Geodetic_CRS_GeoKey/PrimeMeridianLongitudeGeoKey
^| 3077 <| Units_GeoKeys/UnitSizeGeoKey (Projected Linear)
^| 3078 <| Projection_Definition_GeoKeys/ProjAngularParameters (Standard Parallel 1)
^| 3079 <| Projection_Definition_GeoKeys/ProjAngularParameters (Standard Parallel 2)
^| 3080 <| Projection_Definition_GeoKeys/ProjAngularParameters (Natural Oriding Longitude)
^| 3081 <| Projection_Definition_GeoKeys/ProjAngularParameters (Natural Origine Latitude)
^| 3082 <| Projection_Definition_GeoKeys/ProjLinearParameters (False Easting)
^| 3083 <| Projection_Definition_GeoKeys/ProjLinearParameters (False Northing)
^| 3084 <| Projection_Definition_GeoKeys/ProjAngularParameters (False Origin Longitude)
^| 3085 <| Projection_Definition_GeoKeys/ProjAngularParameters (False Origin Latitude)
^| 3086 <| Projection_Definition_GeoKeys/ProjLinearParameters (False Origin Easting)
^| 3087 <| Projection_Definition_GeoKeys/ProjLinearParameters (False Origin Northing)
^| 3088 <| Projection_Definition_GeoKeys/ProjAngularParameters (Center Longitude)
^| 3089 <| Projection_Definition_GeoKeys/ProjAngularParameters (Center Latitude)
^| 3090 <| Projection_Definition_GeoKeys/ProjLinearParameters (Projection Center Easting)
^| 3091 <| Projection_Definition_GeoKeys/ProjLinearParameters (Projection Center Northing)
^| 3092 <| Projection_Definition_GeoKeys/ProjScalarParameters (Scale at Natural Origin)
^| 3093 <| Projection_Definition_GeoKeys/ProjScalarParameters (Scale at Center)
^| 3094 <| Projection_Definition_GeoKeys/ProjAzimuthAngleGeoKey
^| 3095 <| Projection_Definition_GeoKeys/ProjAngularParameters (Straight Vertical Pole)
|===

Double GeoKey Tests