==== Double Parameters Test

*Test id:* TIFF_Test/DoubleParameters

*Requirements:* 

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.KeyEntry.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryTIFFTagLocation 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryKeyCount 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryValueOffset
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoDoubleParamsTag.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoDoubleParamsTag.count
|===

*Purpose:* Verify a Double parameter

*Pre-conditions* The GeoKeyDirectory, DoubleValues and GeoKeyOffset values have been set. 

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|GeoKeyDirectory |Global |Location of the GeoTIFF GeoKey directory
|DoubleValues |Global |Location of the Double values for GeoTIFF Double GeoKeys
|GeoKeyOffset |Parameter| Location of this Key Entry Set in the GeoKey directory
|GeoKey |Local |Temporary value of the GeoKey
|KeyLength |Local |Temporary value for the length of the value for the GeoKey
|KeyValueOffset |Local |The location of the GeoKey value in the file 
|===

*Test Process:*

    Locate the Key Entry Set using the GeoKeyDirectory and GeoKeyOffset values.

    Process the second Short integer in the Key Entry Set
        {
        IF value != 34736 THEN error out
        }
    Process the first Short integer in the Key Entry Set
        {
        Set GeoKey to the value
        }
    Process the third Short integer in the Key Entry Set
        {
        Set KeyLength to the value
        }
    Process the fourth Short integer in the Key Entry Set
        {
        SET KeyValueOffset to the value
        }
    SET KeyValueOffset = DoubleValues + (KeyValueOffset * 8)

    Validate the parameter
        Locate the GeoKey value in the following table
        Execute the corresponding test passing KeyLength and KeyValueOffset as parameters

[[Double_GeoKey_Tests]]
[cols="2,4",width="100%", options="header"]
|===
^| GeoKey ^| Test
^| 0 <| ignore
^| 32767 <| TIFFTest/UserDefinedDouble
^| 2053 <| GeodeticCRSParameterKeys/GeogLinearUnitSizeGeoKey
^| 2055 <| GeogAngularUnitSizeGeoKey
^| 2057 <| EllipsoidSemiMajorAxisGeoKey
^| 2058 <| EllipsoidSemiMinorAxisGeoKey
^| 2059 <| EllipsoidInvFlatteningGeoKey
^| 2061 <| PrimeMeridianLongitudeGeoKey
^| 3077 <| ProjectedCRSParameterKeys/ProjLinearUnitSizeGeoKey
^| 3078 <| ProjStdParallel1GeoKey
^| 3079 <| ProjStdParallel2GeoKey
^| 3080 <| ProjNatOriginLongGeoKey
^| 3081 <| ProjNatOriginLatGeoKey
^| 3082 <| ProjFalseEastingGeoKey
^| 3083 <| ProjFalseNorthingGeoKey
^| 3084 <| ProjFalseOriginLongGeoKey
^| 3085 <| ProjFalseOriginLatGeoKey
^| 3086 <| ProjFalseOriginEastingGeoKey
^| 3087 <| ProjFalseOriginNorthingGeoKey
^| 3088 <| ProjCenterLongGeoKey
^| 3089 <| ProjCenterLatGeoKey
^| 3090 <| ProjCenterEastingGeoKey
^| 3091 <| ProjCenterNorthingGeoKey
^| 3092 <| ProjScaleAtNatOriginGeoKey
^| 3093 <| ProjScaleAtCenterGeoKey
^| 3094 <| ProjAzimuthAngleGeoKey
^| 3095 <| ProjStraightVertPoleLongGeoKey
|===

Double GeoKey Tests