==== ASCII Parameters Test

*Test id:* TIFF_Test/AsciiParameters

*Requirements:* 

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.KeyEntry.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryTIFFTagLocation 
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryKeyCount 
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryValueOffset
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoAsciiParamsTag.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoAsciiParamsTag.count
|http://www.opengis.net/spec/GeoTIFF/1.1/req/CitationGeoKeys 
|===

*Purpose:* Verify an ASCII parameter

*Pre-conditions* The GeoKeyDirectory, ASCIIValues and GeoKeyOffset values have been set. 

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|GeoKeyDirectory |Global |Location of the GeoTIFF GeoKey directory
|ASCIIValues |Global |Location of the ASCII values for GeoTIFF ASCII GeoKeys
|GeoKeyOffset |Parameter| Location of this Key Entry Set in the GeoKey directory
|GeoKey |Local |Temporary value of the GeoKey
|KeyLength |Local |Temporary value for the length of the value for the GeoKey
|KeyValueOffset |Local |The location of the GeoKey value in the file 
|===

*Test Process:*

    Locate the Key Entry Set using the GeoKeyDirectory and GeoKeyOffset values.

    Process the second Short integer in the Key Entry Set
        {
        IF value != 34737 THEN error out
        }
    Process the first Short integer in the Key Entry Set
        {
        Set GeoKey to the value
        }
    Process the third Short integer in the Key Entry Set
        {
        Set KeyLength to the value
        }
    Process the fourth Short integer in the Key Entry Set
        {
        SET KeyValueOffset to the value
        }
    SET KeyValueOffset = AsciiValues + KeyValueOffset

    Read a KeyLength ASCII string values from the GeoTIFF file starting at KeyValueOffset.
        - The individual strings are delimited by the "|" character.
        - The set of ASCII strings is null terminated.
    Validate the value
        Locate the GeoKey in the following table
        Verify that the values read satisfy the constraints defined in the associated Requirements Class.
        Verify that any GeoKeys required by the associated Requirements Class are present in the GeoKey Directory. 

[[ASCII_GeoKey_Tests]]
[cols="2,4",width="100%", options="header"]
|===
^| GeoKey 
^| Requirements Class
^| 1026 <| CitationGeoKeys (GTCitationGeoKey)
^| 2049 <| CitationGeoKeys (GeodeticCitationGeoKey)
^| 3073 <| CitationGeoKeys (ProjectedCitationGeoKey)
^| 4097 <| CitationGeoKeys (VerticalCitationGeoKey)
|===

