=== Short Parameters Test

*Test id:* TIFF_Test/ShortParameters

*Requirements:* 

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.KeyEntry.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryTIFFTagLocation 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryKeyCount 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoKeyDirectoryTag.keyEntryValueOffset
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoAsciiParamsTag.ID 
|http://www.opengis.net/spec/GeoTIFF/1.1/GeoAsciiParamsTag.count
|===

*Purpose:* Verify an ASCII parameter

*Pre-conditions* The GeoKeyDirectory, ASCIIValues and GeoKeyOffset values have been set. 

*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|GeoKeyDirectory |Global |Location of the GeoTIFF GeoKey directory
|ASCIIValues |Global |Location of the ASCII values for GeoTIFF ASCII GeoKeys
|GeoKeyOffset |Parameter| Location of this Key Entry Set in the GeoKey directory
|GeoKey |Local |Temporary value of the GeoKey
|KeyLength |Local |Temporary value for the length of the value for the GeoKey
|KeyValueOffset |Local |The location of the GeoKey value in the file 
|===

*Test Process:*

    Locate the Key Entry Set using the GeoKeyDirectory and GeoKeyOffset values.

    Process the second Short integer in the Key Entry Set
        {
        IF value != 34737 THEN error out
        }
    Process the first Short integer in the Key Entry Set
        {
        Set GeoKey to the value
        }
    Process the third Short integer in the Key Entry Set
        {
        Set KeyLength to the value
        }
    Process the fourth Short integer in the Key Entry Set
        {
        SET KeyValueOffset to the value
        }
    SET KeyValueOffset = AsciiValues + KeyValueOffset

    Validate the parameter
        Locate the GeoKey value in the following table
        Execute the corresponding test passing KeyLength and KeyValueOffset as parameters

[[ASCII_GeoKey_Tests]]
[cols="2,4",width="100%", options="header"]
|===
^| GeoKey 
^| Test
^| 1026 <| GeoTIFFConfigurationKeys/GTCitationGeoKey
^| 1049 <| GeodeticCRSParameterKeys/GeodeticCitaionGeoKey
^| 3073 <| ProjectedCRSParameterKeys/ProjectedCitationGeoKey
^| 4097 <| VerticalCRSParameterKeys/VerticalCitationGeoKey
|===

