==== Short Parameters Test

*Test id:* http://www.opengis.net/spec/GeoTIFF/1.1/conf/ShortParameters

*Requirements:*

[width="100%"]
|===
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.KeyEntry.ID
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryTIFFTagLocation
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryKeyCount
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoKeyDirectoryTag.keyEntryValueOffset
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoShortParams.Criteria
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeoShortParams.Location
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GTModelTypeGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GTRasterTypeGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeodeticCRSGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/GeodeticDatumGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/PrimeMeridianGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/UnitsGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/EllipsoidGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/ProjectedCRSGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/ProjectionGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/ProjMethodGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/VerticalGeoKey
|http://www.opengis.net/spec/GeoTIFF/1.1/req/VerticalDatumGeoKey
|===

*Purpose:* Verify a Short parameter

*Pre-conditions* The GeoKeyDirectory and GeoKeyOffset values have been set
*Test Variables:*

[cols=">20,^20,<80",width="100%", Options="header"]
|===
^|**Variable** ^|**Scope** ^|**Description**
|GeoKeyDirectory |Global |Location of the GeoTIFF GeoKey directory
|GeoKeyOffset |Parameter| Location of this Key Entry Set in the GeoKey directory
|GeoKey |Local |Temporary value of the GeoKey
|KeyLength |Local |Temporary value for the length of the value for the GeoKey
|KeyValueOffset |Local |The location of the GeoKey value in the file
|===

*Test Process:*

    Locate the Key Entry Set using the GeoKeyDirectory and GeoKeyOffset values.

    Process the second Short integer in the Key Entry Set
        {
        IF value != 0 OR 34735 THEN error out
        }
    Process the first Short integer in the Key Entry Set
        {
        SET GeoKey to the value
        }
    Process the third Short integer in the Key Entry Set
        {
        SET KeyLength to the value
        }
    IF KeyLength = 1 THEN
        SET KeyValueOffset = GeoKeyDirectory + GeoKeyOffset + 6
    ELSE
        {
        Process the fourth Short integer in the Key Entry Set
            {
            SET KeyValueOffset to the value
            }
        SET KeyValueOffset = GeoKeyDirectory + (KeyValueOffset * 2)
        }

    Read a KeyLength Short values from the GeoTIFF file starting at KeyValueOffset.
    Validate the value
        Locate the GeoKey in the following table
        Verify that the values read satisfy the constraints defined in the associated Requirements Class.
        Verify that any GeoKeys required by the associated Requirements Class are present in the GeoKey Directory.

[[_ShortGeoKey_Tests]]
[cols="1,4",width="75%", options="header"]
|===
^| GeoKey ^| Requirements Class
^| 0 <| ignore
^| 1024 <| GTModelTypeGeoKey
^| 1025 <| GTRasterTypeGeoKey
^| 2048 <| GeodeticCRSGeoKey
^| 2050 <| GeodeticDatumGeoKey
^| 2051 <| PrimeMeridianGeoKey
^| 2052 <| UnitsGeoKey (Linear Units)
^| 2054 <| UnitsGeoKey (Angular Units)
^| 2056 <| EllipsoidGeoKey
^| 2060 <| UnitsGeoKey (Azimuth Units)
^| 3072 <| ProjectedCRSGeoKey
^| 3074 <| ProjectionGeoKey
^| 3075 <| ProjMethodGeoKey
^| 3076 <| UnitsGeoKey (Linear Units)
^| 4096 <| VerticalGeoKey
^| 4098 <| VerticalDatumGeoKey
^| 4099 <| UnitsGeoKey (Vertical Units)
|===
